### ISSUE TITLE
hey uh do you wanna help with my more complete fnf godot engine?

### ISSUE THREAD

**Issue by rayanmargham** [osogames24fanosogames/FNF---Godot-Engine#2]
i can see your tryna make a fnf engine in godot thing is i've been working on mine for 3-4 months and we seriously need more people to help do you wanna?

**Comment by osogames24fanosogames** [comment]
Sorry it took me 15 days to reply. I would like to help with yours, but I kinda can't at this moment because of school. Also, speaking of which, I'm still technically learning godot as of sending this.

**Comment by rayanmargham** [comment]
Understandable whenever you are able you can always just send another message
